name: spline_dev
channels:
  - conda-forge
dependencies:
  - bump2version
  - python  # gh runner will pin automatically
  - numpy =1.21
  - cmake =3.23
  - ninja
  - setuptools
  - pybind11 >=2.8
  - gcc =9
  - gxx =9
