# <<<  Compiler Stuff  >>>
c_compiler:
    - clang                            # [osx]
    - gcc                              # [linux]
    - vs2017                           # [win]

cxx_compiler:
    - clangxx                          # [osx]
    - gxx                              # [linux]
    - vs2017                           # [win]

c_compiler_version:
    - 10                               # [linux]
    - 10                               # [osx and x86_64]
    - 13                               # [osx and arm64]

cxx_compiler_version:
    - 10                               # [linux]
    - 10                               # [osx and x86_64]
    - 13                               # [osx and arm64]

python:
    - 3.8                              # [not osx]
    - 3.9
    - 3.10
    # - 3.11

numpy:
    # - 1.19                             # [not arm64]
    # - 1.20                             # [not arm64]
    - 1.21

CONDA_BUILD_SYSROOT:
     - /Users/runner/MacOSX10.9.sdk      # [osx and x86_64]