package:
  name: spline
  version: "0.11.1dev0"

source:
     - path: ../../..

build:
  number: 1
  ignore_run_exports_from:
    # - cuda-nvcc_linux-64                   # [linux]
  script_env:
    - CUDAToolkit_INCLUDE_DIR
    - CUDA_CUDART

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - cmake =3.25
    - ninja
    - pip =22.1
    # - cuda-nvcc_linux-64 =12.1.1            # [linux]  # 12.1 not yet available

  host:
    - python
    - numpy {{ numpy }}
    - pybind11 >=2.8

  run:
    - python
    - {{ pin_compatible('numpy', max_pin='x.x') }}

# test:
#     imports:
#       - spline
#     requires:
#       - pytest
#     source-files:
#       - python/test/test_basic.py
#     commands:
#       - pytest -s python/test/test_basic.py

about:
    home: https://rieslab.de
    summary: "Cubic Spline PSF Implementation"
    description: "Tbd."
