name: Build SplinePSF and upload to Anaconda Cloud


# this will be on release at some point
on: [push]

jobs:
  # build-linux:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
    
  #   - name: Install conda build libraries
  #     run: |
  #       $CONDA/bin/conda install conda-build anaconda-client
    
  #   - name: Build SplinePSF
  #     run: |
  #       cd ./dist_tools/conda
  #       $CONDA/bin/conda-build -c conda-forge spline

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install conda build libraries
      # fails here; conda permissions issue with these two lines:
      # run: |
      #   $CONDA/bin/conda install conda-build anaconda-client

      # try using a new env instead of base env to avoid perms issue
      shell: bash -l {0}
      run: |
        $CONDA/bin/conda create --name build_clean conda-build anaconda-client
        source $CONDA/bin/conda activate build_clean
        cd ./dist_tools/conda
        $CONDA/bin/conda-build -c conda-forge spline
    
    # - name: Build SplinePSF
    #   run: |
    #     cd ./dist_tools/conda
    #     $CONDA/bin/conda-build -c conda-forge spline



  # Windows build in progress, barely started:
  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
    
  #   - name: Install conda build libraries

  #     # this not updated yet

  #     run: |
  #       $CONDA/bin/conda install conda-build anaconda-client
  #     shell: cmd
    
  #   - name: Build SplinePSF
  #     run: |
  #       cd ./dist_tools/conda
  #       $CONDA/bin/conda-build -c conda-forge spline


    

    # could have a pytest step here, with upload termination if it fails


    # not working; not really started
    # - name: Upload to Anaconda Cloud
    #   run: |
    #     # this is entirely wrong; needs correct paths from previous step,
    #     #   plus needs secrets for login before upload; also needs logout?
    #     $CONDA/bin/anaconda upload -u Turagalab /path/to/output/file/spline-blah-blah.tar.bz2