name: Build SplinePSF and upload to Anaconda Cloud


# this will be on release at some point
on: [push]

jobs:
  # build-linux:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
    
  #   - name: Install conda build libraries
  #     # for Linux, we can use the provided conda
  #     run: |
  #       $CONDA/bin/conda install conda-build anaconda-client
    
  #   - name: Build SplinePSF
  #     run: |
  #       cd ./dist_tools/conda
  #       $CONDA/bin/conda-build -c conda-forge spline

  # build-macos:
  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8

  #   - uses: conda-incubator/setup-miniconda@v2
  #     # for Mac, the built-in conda has permissions issues; 
  #     #   we use a third-party action instead; note we need to
  #     #   use the "bash -l {0}" shell to ensure login files are run
  #     #   so conda env vars will be set
  #     with:
  #       auto-update-conda: true
  #       python-version: 3.8
  #   - name: Install conda build libraries
  #     shell: bash -l {0}
  #     run: |
  #       conda install conda-build anaconda-client

  #   - name: Build SplinePSF
  #     shell: bash -l {0}
  #     run: |
  #       cd ./dist_tools/conda
  #       conda-build -c conda-forge spline


  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - uses: conda-incubator/setup-miniconda@v2
      # as with Mac, easier to use the third-party setup
      with:
        auto-update-conda: true
        python-version: 3.8

    - name: Install conda build libraries
      shell: powershell
      run: |
        conda install conda-build anaconda-client


    
    # - name: Build SplinePSF
    #   run: |
    #     cd ./dist_tools/conda
    #     $CONDA/bin/conda-build -c conda-forge spline


    

    # could have a pytest step here, with upload termination if it fails


    # not working; not really started
    # - name: Upload to Anaconda Cloud
    #   run: |
    #     # this is entirely wrong; needs correct paths from previous step,
    #     #   plus needs secrets for login before upload; also needs logout?
    #     $CONDA/bin/anaconda upload -u Turagalab /path/to/output/file/spline-blah-blah.tar.bz2